import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const notoSansJP = Noto_Sans_JP({
  subsets: ["latin", "vietnamese"], // Include Japanese
  variable: "--font-noto-sans-jp",
  weight: ["100", "200", "300", "400"], // You can adjust these weights
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSansJP.variable} font-sans antialiased bg-gray-200`}
      >
        {children}
      </body>
    </html>
  );
}
